---
version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/opt/offer-search

  elastic:
    image: docker.io/bitnami/elasticsearch:7
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
  grafana:
    image: grafana/grafana:8.2.6
    env_file:
      - .grafana/config
    ports:
      - '3000:3000'

volumes:
  elasticsearch_data:
    driver: local
